fix: in some cases, unstable flag errors occur when the uses or leaves option is specified
Issue:
 Steps:
  1. Prepare Deno v1.2.0.
  2. Run "deno cache --unstable https://deno.land/std@0.61.0/node/module.ts".
  3. Run this script with the --uses or --leaves option.
  *This issue is reproduced in cases where modules that
   require the --unstable option when runnning "deno info" have been cached.
 Actual:
  Following errors occur:
  error: TS2339 [ERROR]: Property 'loadavg' does not exist on type 'typeof Deno'. 'Deno.loadavg' is an unstable API. Did you forget to run with the '--unstable' flag?
  (omit)
 Expected:
  Module search should be done without any errors.